config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end  
  
  root 'listings#index'
  
  get 'about' => 'pages#about'

  get 'contact' => 'pages#contact'
  
  get 'blog' => 'pages#blog'
  
  get 'investors' => 'pages#investors'
  
  get 'our_process' => 'pages#our_process'
  
  get 'properties' => 'pages#properties'
  
  get 'property_locator' => 'pages#property_locator'
  
  get 'realtors' => 'pages#realtors'
  
  get 'seller' => "listings#seller"
  
  get 'sales' => "orders#sales"
  
  get 'purchases' => "orders#purchases"

end

app/models/listing.rb
class Listing < ActiveRecord::Base
    if Rails.env.development?
        has_attached_file :image, styles: { medium: "100x100>", thumb: "50x50#" }, default_url: "default.jpg"
    else    
        has_attached_file :image, styles: { medium: "100x100>", thumb: "50x50#" }, default_url: "default.jpg",
            :storage => :dropbox,
            :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
            :path => ":style/:id_:filename"
    end
    
    validates :status, :property_type, :asking_price, presence: true
    validates :asking_price, numericality: { greater_than: 0}
    #validates_attachment_presence :image
    
    belongs_to :user
    has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
    validates :address, :city, :state, presence: true
    
    belongs_to :listing
    belongs_to :buyer, class_name: "User"
    belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :name, presence: true
  
  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end
  
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:status, :lead_type, :property_type, :location, :avr, :asking_price, :repair_cost, :profit, :image)
    end
    
    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end
  
  def purchases
     @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user
    
    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id
    
    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]
    
    begin
      charge = Stripe::Charge.create(
        :amount => (@listing.asking_price = 100).floor,
        :currency => "usd",
        :source => token
        )
      flash[:notice] = "Thanks for ordering!"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end  

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
  
  def blog
  end
  
  def investors
  end
  
  def our_process
  end
  
  def properties
  end
  
  def property_locator
  end
  
  def realtors
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
        return '' if resource.errors.empty?
        
        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg)}.join
        sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)
        
        html = <<-HTML
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4>#{sentence}</h4>
            #{messages}
        </div>
        HTML
        
        html.html_safe
    end
end    

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright 2016 | All Rights Resevered | Rehab Buyers Club</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Rehab Buyers Club</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About Us', about_path %></li>
        <li><%= link_to 'Investors', investors_path %></li>
        <li><%= link_to 'Contact Us', contact_path %></li>
          <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Seller Account<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Manage Listings', seller_path %></li>
            <li><%= link_to 'Sales History', sales_path %></li>
          </ul>
        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Purchase History', purchases_path %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
          <% else %>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Log In', new_user_session_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
    
  </div><!-- /.container-fluid -->
</nav>

<nav class="navbar navbar-inverse bottomrow">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
        <li><%= link_to 'Properties For Sale', properties_path %></li>
        <li><%= link_to 'Our Company', about_path %></li>
        <li><%= link_to 'How It Works', our_process_path %></li>
        <li><%= link_to 'Realtors', realtors_path %></li>
        <li><%= link_to 'Property Locator', property_locator_path %></li>
        <li><%= link_to 'Blog', blog_path %></li>
    
      </ul>
    </div><!-- /.navbar-collapse -->
    
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rehab Buyers Club | Chicago's Marketplace for Investment Deals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
<%= render 'layouts/header' %>


  <%= flash.each do |name, msg| %>     
       <% if msg.is_a?(String) %>
         <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
           <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
           <%= content_tag :div, msg, :id => "flash_#{name}" %>
         </div>
       <% end %>
  <% end %>
<div class="container"> 
  <%= yield %>
<%= render 'layouts/footer' %>
</div> 
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, html: { multipart: true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="form-group">
    <%= f.label :status, 'Status' %>
    <%= f.text_field :status, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :lead_type, 'Lead Type' %>
    <%= f.text_field :lead_type, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :property_type, 'Property Type' %>
    <%= f.text_field :property_type, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location, 'Location' %>
    <%= f.text_field :location, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :avr, 'After Repaired Value' %>
    <%= f.text_field :avr, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :asking_price, 'Seller Asking Price' %>
    <%= f.text_field :asking_price, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :repair_cost, 'Estimated Rehab Cost' %>
    <%= f.text_field :repair_cost, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :profit, 'Potential Profit' %>
    <%= f.text_field :profit, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image, 'Load Property Image' %>
    <%= f.file_field :image, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success"%>
  </div>
<% end %>
</div>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class:"btn btn-link" %> |
<%= link_to 'Back', listings_path, class:"btn btn-link" %>

app/views/listings/index.html.erb
<!--Banner Section-->
  	
  	<div class="banner container">
 	
  	<div class="row">
  	  <div class="col-md-4 col-md-offset-1">
  	    <h3>Chicago Investment<br>Properties Under $100K</h3>
  	    <p class="subhero">Enter your information HERE to gain access to<br>HANDYMAN deals in the Chicago Area.</p>
  	    <p>Also get emails when we get new cheap properties in our inventory</p>
  	    <p class="subhero">Just Complete This<br>Quick Form!</p>
  	  </div>
  	  
  	<div class="col-md-5 col-md-offset-2">
  	<div class="sidebar">
  		<form>
  			<h4>See Our Local Fixer Upper Properties - FREE</h4><br>
  			<p>Non MLS Investment Properties, Many are under $100K!</p>
  				<div class="form-group">
    				<label for="email1">Enter Your First & Last Name</label>
    				<form class="form-inline">
              <div class="form-group">
              <label class="sr-only" for="exampleInputEmail3">Email address</label>
              <input type="email" class="form-control" id="email3" placeholder="First Name">
          </div>
          <div class="form-group">
            <label class="sr-only" for="password3">Password</label>
              <input type="password" class="form-control" id="password3" placeholder="Last Name">
          </div>
  				</div>
  				
  				<div class="form-group">
    				<label for="email1">What Kind of Buyer Are You?</label>
    				<select class="form-control">
  						<option>Less than $100,000</option>
  						<option>$100,000-$250,000</option>
  						<option>$250,000-$500,000</option>
  						<option>$500,000-$1,000,000</option>
  						<option>$1,000,000+</option>
					</select>
  				</div>
  <div class="form-group">
              <label class="sr-only" for="email3">Email</label>
              <input type="email" class="form-control" id="email3" placeholder="Email">
          </div>
  		</form> 
  		</div><!--close col-->
  		</div><!--close row-->
  		</div>
  	</div><!--close banner-->

<h1>Listing Listings</h1>
<div class="container">
  <div class="row">
     <% @listings.each do |listing| %>
     <div class="col-md-12">
    <div class="col-md-1">
      <div class="thumbnail">
      <%= link_to image_tag(listing.image.url), listing %>
      </div>
    </div>
    <div class="col-md-3 list1">
      <p>Status:</p>
      <p>Lead Type:</p>
      <p>Property Type:</p>
      <p>Location:</p>
    </div>
    <div class="col-md-2">
      <%= listing.status %><br>
      <%= listing.lead_type %><br>
      <%= listing.property_type %><br>
      <%= listing.location %>
    </div>
    <div class="col-md-3 list1">
      <p>Estimated After Repair Value:</p>
      <p>Seller's Asking Price:</p>
      <p>Estimated Cost of Repairs:</p>
      <p>Profit Potential of:</p>
    </div>
    <div class="col-md-2">
      <%= number_to_currency(listing.avr) %><br>
      <%= number_to_currency(listing.asking_price) %><br>
      <%= number_to_currency(listing.repair_cost) %><br>
      <%= number_to_currency(listing.profit) %>
    </div>
    <div class="col-md-1">
      <p><%= "Property Listed by #{listing.user.name}" %></p>
      <%= link_to 'See Full Details', listing, class:"btn btn-success btn-xs" %><br>
    </div>
    
    </div>
   <% end %> 
    
  </div>  
  </div>
  
<br>
<% if user_signed_in? %>
  <%= link_to 'Add a New Property', new_listing_path, class:"btn btn-link" %>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class:"btn btn-link" %>

app/views/listings/seller.html.erb
<!--Banner Section-->
  	
  	<div class="banner container">
 	
  	<div class="row">
  	  <div class="col-md-4 col-md-offset-1">
  	    <h3>Chicago Investment<br>Properties Under $100K</h3>
  	    <p class="subhero">Enter your information HERE to gain access to<br>HANDYMAN deals in the Chicago Area.</p>
  	    <p>Also get emails when we get new cheap properties in our inventory</p>
  	    <p class="subhero">Just Complete This<br>Quick Form!</p>
  	  </div>
  	  
  	<div class="col-md-5 col-md-offset-2">
  	<div class="sidebar">
  		<form>
  			<h4>See Our Local Fixer Upper Properties - FREE</h4><br>
  			<p>Non MLS Investment Properties, Many are under $100K!</p>
  				<div class="form-group">
    				<label for="exampleInputEmail1">Enter Your First & Last Name</label>
    				<form class="form-inline">
              <div class="form-group">
              <label class="sr-only" for="exampleInputEmail3">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail3" placeholder="First Name">
          </div>
          <div class="form-group">
            <label class="sr-only" for="exampleInputPassword3">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword3" placeholder="Last Name">
          </div>
  				</div>
  				
  				<div class="form-group">
    				<label for="exampleInputEmail1">What Kind of Buyer Are You?</label>
    				<select class="form-control">
  						<option>Less than $100,000</option>
  						<option>$100,000-$250,000</option>
  						<option>$250,000-$500,000</option>
  						<option>$500,000-$1,000,000</option>
  						<option>$1,000,000+</option>
					</select>
  				</div>
  <div class="form-group">
              <label class="sr-only" for="exampleInputEmail3">Email</label>
              <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Email">
          </div>
  		</form> 
  		</div><!--close col-->
  		</div><!--close row-->
  		</div>
  	</div><!--close banner-->

<h1>Listing Listings</h1>
<div class="container">
  <div class="row">
     <% @listings.each do |listing| %>
     <div class="col-md-12">
    <div class="col-md-1">
      <div class="thumbnail">
      <%= link_to image_tag(listing.image.url), listing %>
      </div>
    </div>
    <div class="col-md-3 list1">
      <p>Status:</p>
      <p>Lead Type:</p>
      <p>Property Type:</p>
      <p>Location:</p>
    </div>
    <div class="col-md-2">
      <%= listing.status %><br>
      <%= listing.lead_type %><br>
      <%= listing.property_type %><br>
      <%= listing.location %>
    </div>
    <div class="col-md-3 list1">
      <p>Estimated After Repair Value:</p>
      <p>Seller's Asking Price:</p>
      <p>Estimated Cost of Repairs:</p>
      <p>Profit Potential of:</p>
    </div>
    <div class="col-md-2">
      <%= number_to_currency(listing.avr) %><br>
      <%= number_to_currency(listing.asking_price) %><br>
      <%= number_to_currency(listing.repair_cost) %><br>
      <%= number_to_currency(listing.profit) %>
    </div>
    <div class="col-md-1">
      <p><%= "Property Listed by #{listing.user.name}" %></p>
      <%= link_to 'See Full Details', listing, class:"btn btn-success btn-xs" %><br>
      <% if (user_signed_in?) && (current_user == listing.user) %>
        <%= link_to 'Edit', edit_listing_path(listing), class:"btn btn-link" %><br>
        <%= link_to 'Delete Listing', listing, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-link" %>
      <% end %>
    </div>
    
    </div>
   <% end %> 
    
  </div>  
  </div>
  
<br>
<% if user_signed_in? %>
  <%= link_to 'Add a New Property', new_listing_path, class:"btn btn-link" %>
<% end %>

app/views/listings/show.html.erb
<div class="container">
<%= image_tag @listing.image.url(:medium) %>

<p>
  <strong>Status:</strong>
  <%= @listing.status %>
</p>

<p>
  <strong>Lead type:</strong>
  <%= @listing.lead_type %>
</p>

<p>
  <strong>Property type:</strong>
  <%= @listing.property_type %>
</p>

<p>
  <strong>Location:</strong>
  <%= @listing.location %>
</p>

<p>
  <strong>Avr:</strong>
  <%= number_to_currency(@listing.avr) %>
</p>

<p>
  <strong>Asking price:</strong>
  <%= number_to_currency(@listing.asking_price) %>
</p>

<p>
  <strong>Repair cost:</strong>
  <%= number_to_currency(@listing.repair_cost) %>
</p>

<p>
  <strong>Profit:</strong>
  <%= number_to_currency(@listing.profit) %>
</p>
<%= link_to "Buy It Now", new_listing_order_path(@listing) %>

<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class:"btn btn-link", data: { no_turolink: true} %> |
<% end %>
<%= link_to 'Back', listings_path, class:"btn btn-link", class:"btn btn-link" %>
</div>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
    <h3><%= @listing.location %></h3>
    <h4><%= number_to_currency(@listing.asking_price) %></h4>
  </div> 
  <div class="col-md-8">
    
<%= form_for([@listing, @order]) do |f| %>
  <% if @order.errors.any? %>
  <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>Javascript is not enabled and is required for this form.  First enable it in your web browser settings.</noscript>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <div class="row">
      <div class="col-md-8">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, { :name => nil, 'data-stripe' => "number", class:"form-control"} %>
      </div>
      <div class="col-md-4">
        <%= label_tag :card_code, "CVC" %>
        <%= text_field_tag :card_code, nil, { :name => nil, 'data-stripe' => "cvc", class:"form-control"} %>
      </div>
  </div>
  </div>
  
  <div class="form-group">
    <%= label_tag nil, "Expiration Date" %>
    <div class="row">
      <div class="col-md-3">
        <%= select_month nil, {use_two_digit_numbers: true}, { :name => nil, 'data-stripe' => "exp-month", class:"form-control"} %>
      </div>
      <div class="col-md-3">
        <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10}, { :name => nil, 'data-stripe' => "exp-year", class:"form-control"} %>
      </div>
  </div>
  </div>
  <div class="form-group">
    <%= f.submit "Complete Order", class:"btn btn-primary" %>
  </div>
<% end %>
</div>
</div>

app/views/orders/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', listing_orders_path %>

app/views/orders/purchases.html.erb
<h1>Listings Purchased</h1>
<div class="container">
  <div class="row">
     <% @orders.each do |order| %>
     <div class="col-md-12">
    <div class="col-md-1">
      <div class="thumbnail">
      <%= image_tag order.listing.image.url(:thumb) %>
      </div>
    </div>
    <div class="col-md-3 list1">
      <p>Status:</p>
      <p>Lead Type:</p>
      <p>Property Type:</p>
      <p>Location:</p>
    </div>
    <div class="col-md-2">
      <%= order.listing.status %><br>
      <%= order.listing.lead_type %><br>
      <%= order.listing.property_type %><br>
      <%= order.listing.location %>
      <%= order.seller.name %>
      <%= order.created_at.strftime("%B %-d, %Y") %>
    </div>
    <div class="col-md-3 list1">
      <p>Estimated After Repair Value:</p>
      <p>Seller's Asking Price:</p>
      <p>Estimated Cost of Repairs:</p>
      <p>Profit Potential of:</p>
    </div>
    <div class="col-md-2">
      <%= number_to_currency(listing.avr) %><br>
      <%= number_to_currency(listing.asking_price) %><br>
      <%= number_to_currency(listing.repair_cost) %><br>
      <%= number_to_currency(listing.profit) %>
    </div>
    </div>
  </div>  
  </div>

app/views/orders/sales.html.erb
<h1>Listings Sold</h1>
<div class="container">
  <div class="row">
     <% @orders.each do |order| %>
     <div class="col-md-12">
    <div class="col-md-1">
      <div class="thumbnail">
      <%= image_tag order.listing.image.url(:thumb %>
      </div>
    </div>
    <div class="col-md-3 list1">
      <p>Status:</p>
      <p>Lead Type:</p>
      <p>Property Type:</p>
      <p>Location:</p>
    </div>
    <div class="col-md-2">
      <%= order.listing.status %><br>
      <%= order.listing.lead_type %><br>
      <%= order.listing.property_type %><br>
      <%= order.listing.location %>
      <%= order.buyer.name %>
      <%= order.created_at.strftime("%B %-d, %Y") %>
    </div>
    <div class="col-md-3 list1">
      <p>Estimated After Repair Value:</p>
      <p>Seller's Asking Price:</p>
      <p>Estimated Cost of Repairs:</p>
      <p>Profit Potential of:</p>
    </div>
    <div class="col-md-2">
      <%= number_to_currency(listing.avr) %><br>
      <%= number_to_currency(listing.asking_price) %><br>
      <%= number_to_currency(listing.repair_cost) %><br>
      <%= number_to_currency(listing.profit) %>
    </div>
    
    </div>
   <% end %> 
    
  </div>  
  </div>
  
<br>
<% if user_signed_in? %>
  <%= link_to 'Add a New Property', new_listing_path, class:"btn btn-link" %>
<% end %>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>How we do what we do</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Our Phone</p>
<p>email us</p>

app/views/pages/our_process.html.erb
<h1>This is how it works</h1>
<p>3 simple steps to build your real estate empire</p>